name: whaleybar
root: .

windows:
  - whaleybar:
      layout: even-horizontal
      panes:
        - client:
            - cd client
            - npm run dev
        - server:
            - cd server
            - deno task start
