name: Deploy
on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install client dependencies
        run: cd client && deno install --allow-scripts && deno task build

      - name: Move client to server
        run: cd server && deno task move:client

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: whaleybar
          entrypoint: ./index.ts
          root: ./server
